shopware-operator:
  image: 
    # pullPolicy: Always

prometheus:
  server:
    clusterRoleNameOverride: shopware-prometheus-server

minio:
  storageClassName: standard

store:
  # We use traefik.me to resolve to 127.0.0.1
  # Enter your DNS name for the shop.
  # This will make sure that your sales-channel is set up correctly and the ingress is using the host address.
  # host: shop.shopware.systems
  host: localhost.traefik.me
  container:
    # imagePullPolicy: Always
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: info
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
      nested:
        type: group
        members: [stderr, file_log]
      stderr:
        type: stream
        path: php://stderr
        level: info
      file_log:
        type: stream
        path: "/var/log/shopware.log"
        level: info
        formatter: 'monolog.formatter.json'
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      business_event_handler_buffer:
        level: info
  sidecarLogging:
    image:
      repository: cr.fluentbit.io/fluent/fluent-bit
      tag: 3.1.4
      # pullPolicy: IfNotPresent
    # logFfolder: /var/log
    # logFile: shopware.log
    # lokiHost: loki-gateway.loki.svc.cluster.local

grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          uid: prometheus
          url: http://shopware-prometheus-server.shopware.svc.cluster.local
        - name: Loki
          type: loki
          url: http://loki-gateway.loki.svc.cluster.local

percona:
  database:
    storageClassName: standard
    nodeSelector:
      kubernetes.io/arch: arm64

pxc-operator:
  nodeSelector:
    kubernetes.io/arch: arm64